### ISSUE TITLE
Change from Google Docs to Overleaf

### ISSUE THREAD

**Issue by lovelaced** [dcchambers/CHTC-Student-Handbook#5]
overleaf.com

This way it has a native git repository of its own.

**Comment by dcchambers** [comment]
I abandoned the google doc after using that for the initial drafting. I rewrote the guide in LaTeX. Clone/fork/pull the master branch in the repository to get the latest LaTeX version. Easy to then edit in overleaf if desired. I'll look into hosting on overleaf - the nice thing about github is that I can host multiple file types and people can view/download without having an account.

**Comment by dcchambers** [comment]
@lovelaced I abandoned the google doc after using that for the initial drafting. I rewrote the guide in LaTeX. Clone/fork/pull the master branch in the repository to get the latest LaTeX version. Easy to then edit in overleaf if desired. I'll look into hosting on overleaf - the nice thing about github is that I can host multiple file types and people can view/download without having an account.

**Comment by lovelaced** [comment]
Sounds good to me.
